"""add auth tenant roles sessions

Revision ID: 3a7d0af78882
Revises: 0001_initial_schema
Create Date: 2026-01-23 08:07:55.041563

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a7d0af78882'
down_revision = '0001_initial_schema'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_permissions',
    sa.Column('id_row', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('permission_id', sa.String(length=100), nullable=False),
    sa.Column('description_permission', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id_row'),
    sa.UniqueConstraint('permission_id')
    )
    op.create_table('tb_tenants',
    sa.Column('id_row', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('name_tenant', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('create_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id_row'),
    sa.UniqueConstraint('tenant_id')
    )
    op.execute(
        "INSERT INTO tb_tenants (tenant_id, name_tenant) "
        "VALUES ('DEFAULT', 'Default Tenant') "
        "ON CONFLICT (tenant_id) DO NOTHING"
    )
    op.create_table('tb_roles',
    sa.Column('id_row', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('role_id', sa.String(length=50), nullable=False),
    sa.Column('description_role', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('create_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tb_tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('id_row'),
    sa.UniqueConstraint('role_id')
    )
    op.create_index('ix_tb_roles_tenant_id', 'tb_roles', ['tenant_id'], unique=False)
    op.create_table('tb_role_permissions',
    sa.Column('id_row', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('role_id', sa.String(length=50), nullable=False),
    sa.Column('permission_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['tb_permissions.permission_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['tb_roles.role_id'], ),
    sa.PrimaryKeyConstraint('id_row'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_index('ix_tb_role_permissions_permission_id', 'tb_role_permissions', ['permission_id'], unique=False)
    op.create_index('ix_tb_role_permissions_role_id', 'tb_role_permissions', ['role_id'], unique=False)
    op.create_table('tb_sessions',
    sa.Column('id_row', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('id_user', sa.String(length=50), nullable=False),
    sa.Column('csrf_token', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['tb_users.id_user'], ),
    sa.PrimaryKeyConstraint('id_row'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index('ix_tb_sessions_expires_at', 'tb_sessions', ['expires_at'], unique=False)
    op.create_index('ix_tb_sessions_id_user', 'tb_sessions', ['id_user'], unique=False)
    op.create_table('tb_user_roles',
    sa.Column('id_row', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('id_user', sa.String(length=50), nullable=False),
    sa.Column('role_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['tb_users.id_user'], ),
    sa.ForeignKeyConstraint(['role_id'], ['tb_roles.role_id'], ),
    sa.PrimaryKeyConstraint('id_row'),
    sa.UniqueConstraint('id_user', 'role_id', name='uq_user_role')
    )
    op.create_index('ix_tb_user_roles_id_user', 'tb_user_roles', ['id_user'], unique=False)
    op.create_index('ix_tb_user_roles_role_id', 'tb_user_roles', ['role_id'], unique=False)
    op.add_column('tb_users', sa.Column('tenant_id', sa.String(length=50), server_default=sa.text("'DEFAULT'"), nullable=False))
    op.create_foreign_key(None, 'tb_users', 'tb_tenants', ['tenant_id'], ['tenant_id'])
    op.execute(
        "INSERT INTO tb_permissions (permission_id, description_permission) VALUES "
        "('users.read', 'Read users'),"
        "('users.write', 'Create/update/delete users'),"
        "('roles.read', 'Read roles'),"
        "('roles.write', 'Create/update/delete roles') "
        "ON CONFLICT (permission_id) DO NOTHING"
    )
    op.execute(
        "INSERT INTO tb_roles (role_id, description_role, tenant_id) VALUES "
        "('ADM', 'Administrator role', 'DEFAULT'),"
        "('USR', 'Standard user role', 'DEFAULT') "
        "ON CONFLICT (role_id) DO NOTHING"
    )
    op.execute(
        "INSERT INTO tb_role_permissions (role_id, permission_id) VALUES "
        "('ADM', 'users.read'),"
        "('ADM', 'users.write'),"
        "('ADM', 'roles.read'),"
        "('ADM', 'roles.write'),"
        "('USR', 'users.read') "
        "ON CONFLICT (role_id, permission_id) DO NOTHING"
    )
    op.execute(
        "INSERT INTO tb_user_roles (id_user, role_id) "
        "SELECT id_user, 'ADM' FROM tb_users WHERE id_user = 'admin' "
        "ON CONFLICT (id_user, role_id) DO NOTHING"
    )
    op.execute(
        "INSERT INTO tb_user_roles (id_user, role_id) "
        "SELECT id_user, 'USR' FROM tb_users WHERE id_user = 'machine' "
        "ON CONFLICT (id_user, role_id) DO NOTHING"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_users', type_='foreignkey')
    op.drop_column('tb_users', 'tenant_id')
    op.drop_index('ix_tb_user_roles_role_id', table_name='tb_user_roles')
    op.drop_index('ix_tb_user_roles_id_user', table_name='tb_user_roles')
    op.drop_table('tb_user_roles')
    op.drop_index('ix_tb_sessions_id_user', table_name='tb_sessions')
    op.drop_index('ix_tb_sessions_expires_at', table_name='tb_sessions')
    op.drop_table('tb_sessions')
    op.drop_index('ix_tb_role_permissions_role_id', table_name='tb_role_permissions')
    op.drop_index('ix_tb_role_permissions_permission_id', table_name='tb_role_permissions')
    op.drop_table('tb_role_permissions')
    op.drop_index('ix_tb_roles_tenant_id', table_name='tb_roles')
    op.drop_table('tb_roles')
    op.drop_table('tb_tenants')
    op.drop_table('tb_permissions')
    # ### end Alembic commands ###
