-- User tables (aligned with Python schema)

DROP TABLE IF EXISTS tb_users CASCADE;
DROP TABLE IF EXISTS tb_user_status CASCADE;
DROP TABLE IF EXISTS tb_groups CASCADE;

-- Create table: tb_groups
DROP TABLE IF EXISTS tb_groups CASCADE;
CREATE TABLE tb_groups(
    id_row integer GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
    id_group VARCHAR(10) UNIQUE NOT NULL,
    name_group VARCHAR(50) NOT NULL,
    level_group smallint NOT NULL,
    create_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_tb_groups PRIMARY KEY (id_group)
);

-- Create table: tb_user_status
DROP TABLE IF EXISTS tb_user_status CASCADE;
CREATE TABLE tb_user_status(
    id_row integer GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
    status_user VARCHAR(3) UNIQUE NOT NULL,
    description_status VARCHAR(50) NOT NULL,
    create_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_tb_user_status PRIMARY KEY (status_user)
);

-- Create table: tb_users
DROP TABLE IF EXISTS tb_users CASCADE;
CREATE TABLE tb_users(
    id_row integer GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
    id_user VARCHAR(50) UNIQUE NOT NULL,
    name_user VARCHAR(50) NOT NULL,
    mail_user VARCHAR(50) NOT NULL,
    id_group VARCHAR(10) NOT NULL,
    status_user VARCHAR(3) NOT NULL,
    pass_hash VARCHAR(255) NOT NULL,
    create_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_tb_users PRIMARY KEY (id_user),
    CONSTRAINT fk_tb_users_group FOREIGN KEY (id_group) REFERENCES tb_groups (id_group),
    CONSTRAINT fk_tb_users_status FOREIGN KEY (status_user) REFERENCES tb_user_status (status_user)
);

-- Default groups
INSERT INTO tb_groups(id_row, id_group, name_group, level_group, create_date)
VALUES (DEFAULT, 'ADM','Administrator',10,DEFAULT);
INSERT INTO tb_groups(id_row, id_group, name_group, level_group, create_date)
VALUES (DEFAULT, 'USR','User',1,DEFAULT);

-- Default user statuses
INSERT INTO tb_user_status(id_row, status_user, description_status, create_date)
VALUES (DEFAULT,'ENB','Enabled',DEFAULT);
INSERT INTO tb_user_status(id_row, status_user, description_status, create_date)
VALUES (DEFAULT,'DIS','Disabled',DEFAULT);

-- Default users
-- NOTE: pass_hash must be a bcrypt hash when used in production.
INSERT INTO tb_users(id_row, id_user, name_user, mail_user, id_group, status_user, pass_hash, create_date)
VALUES (DEFAULT,'admin','administrator','admin@admin.local','ADM','ENB','CHANGE_ME_BCRYPT_HASH',DEFAULT);
INSERT INTO tb_users(id_row, id_user, name_user, mail_user, id_group, status_user, pass_hash, create_date)
VALUES (DEFAULT,'machine','default machine','machine@machine.local','USR','ENB','CHANGE_ME_BCRYPT_HASH',DEFAULT);
