-- Core trazability tables (aligned with Python schema)

DROP TABLE IF EXISTS href_routing_model CASCADE;
DROP TABLE IF EXISTS href_routing_cell CASCADE;
DROP TABLE IF EXISTS href_cell_line CASCADE;
DROP TABLE IF EXISTS his_proc_item CASCADE;
DROP TABLE IF EXISTS tb_items CASCADE;
DROP TABLE IF EXISTS tb_status CASCADE;
DROP TABLE IF EXISTS tb_models CASCADE;
DROP TABLE IF EXISTS tb_routings CASCADE;
DROP TABLE IF EXISTS tb_cells CASCADE;
DROP TABLE IF EXISTS tb_lines CASCADE;

-- tb_lines
CREATE TABLE tb_lines(
    id_row integer GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
    line_id varchar(50) UNIQUE NOT NULL,
    description_line varchar(50) NOT NULL,
    create_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_tb_lines PRIMARY KEY (id_row)
);

-- tb_cells
CREATE TABLE tb_cells(
    id_row integer GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
    cell_id varchar(50) UNIQUE NOT NULL,
    description_cell varchar(50) NOT NULL,
    create_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_tb_cells PRIMARY KEY (id_row)
);

-- tb_routings
CREATE TABLE tb_routings(
    id_row integer GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
    routing_id varchar(50) UNIQUE NOT NULL,
    description_routing varchar(50) NOT NULL,
    create_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_tb_routings PRIMARY KEY (id_row)
);

-- tb_models
CREATE TABLE tb_models(
    id_row integer GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
    model_id varchar(50) UNIQUE NOT NULL,
    description_model varchar(50) NOT NULL,
    create_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_tb_models PRIMARY KEY (id_row)
);

-- tb_status
CREATE TABLE tb_status(
    id_row integer GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
    status_id varchar(50) UNIQUE NOT NULL,
    description_status varchar(50) NOT NULL,
    CONSTRAINT pk_tb_status PRIMARY KEY (id_row)
);

-- tb_items
CREATE TABLE tb_items(
    id_row integer GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
    item_id varchar(50) UNIQUE NOT NULL,
    model_id varchar(50) NOT NULL,
    line_id varchar(50) NOT NULL,
    location_id smallint NOT NULL,
    cell_id varchar(50) NOT NULL,
    id_user varchar(50) NOT NULL,
    create_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_test_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status_id varchar(50) NOT NULL,
    value1_int integer,
    value2_int integer,
    value3_int integer,
    value4_int integer,
    value5_int integer,
    value1_str varchar(50),
    value2_str varchar(50),
    value3_str varchar(50),
    value4_str varchar(50),
    value5_str varchar(50),
    CONSTRAINT pk_tb_items PRIMARY KEY (id_row),
    CONSTRAINT fk_tb_items_model FOREIGN KEY (model_id) REFERENCES tb_models (model_id),
    CONSTRAINT fk_tb_items_line FOREIGN KEY (line_id) REFERENCES tb_lines (line_id),
    CONSTRAINT fk_tb_items_status FOREIGN KEY (status_id) REFERENCES tb_status (status_id),
    CONSTRAINT fk_tb_items_cells FOREIGN KEY (cell_id) REFERENCES tb_cells (cell_id),
    CONSTRAINT fk_tb_items_users FOREIGN KEY (id_user) REFERENCES tb_users (id_user)
);

-- his_proc_item
CREATE TABLE his_proc_item(
    id_row integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    item_id varchar(50) NOT NULL,
    model_id varchar(50) NOT NULL,
    line_id varchar(50) NOT NULL,
    location_id smallint NOT NULL,
    cell_id varchar(50) NOT NULL,
    id_user varchar(50) NOT NULL,
    create_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_test_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status_id varchar(50) NOT NULL,
    value1_int integer,
    value2_int integer,
    value3_int integer,
    value4_int integer,
    value5_int integer,
    value1_str varchar(50),
    value2_str varchar(50),
    value3_str varchar(50),
    value4_str varchar(50),
    value5_str varchar(50),
    CONSTRAINT pk_his_proc_item PRIMARY KEY (id_row),
    CONSTRAINT fk_his_proc_item_model FOREIGN KEY (model_id) REFERENCES tb_models (model_id),
    CONSTRAINT fk_his_proc_item_line FOREIGN KEY (line_id) REFERENCES tb_lines (line_id),
    CONSTRAINT fk_his_proc_item_status FOREIGN KEY (status_id) REFERENCES tb_status (status_id),
    CONSTRAINT fk_his_proc_item_cells FOREIGN KEY (cell_id) REFERENCES tb_cells (cell_id),
    CONSTRAINT fk_his_proc_item_users FOREIGN KEY (id_user) REFERENCES tb_users (id_user)
);

-- href_cell_line
CREATE TABLE href_cell_line(
    id_row integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cell_id varchar(50) NOT NULL,
    line_id varchar(50) NOT NULL,
    create_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_href_cell_line PRIMARY KEY (id_row),
    CONSTRAINT fk_href_cell_line_cell FOREIGN KEY (cell_id) REFERENCES tb_cells(cell_id),
    CONSTRAINT fk_href_cell_line_line FOREIGN KEY (line_id) REFERENCES tb_lines(line_id),
    CONSTRAINT uq_href_cell_line_cell_line UNIQUE (cell_id, line_id)
);

-- href_routing_cell
CREATE TABLE href_routing_cell(
    id_row integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    routing_id varchar(50) NOT NULL,
    cell_id varchar(50) NOT NULL,
    location_id smallint NOT NULL,
    create_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_href_routing_cell PRIMARY KEY (id_row),
    CONSTRAINT fk_href_routing_cell_cell FOREIGN KEY (cell_id) REFERENCES tb_cells(cell_id),
    CONSTRAINT fk_href_routing_cell_route FOREIGN KEY (routing_id) REFERENCES tb_routings(routing_id),
    CONSTRAINT uq_href_routing_cell_route_cell_loc UNIQUE (routing_id, cell_id, location_id)
);

-- href_routing_model
CREATE TABLE href_routing_model(
    id_row integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    routing_id varchar(50) NOT NULL,
    model_id varchar(50) NOT NULL,
    location_id smallint NOT NULL,
    CONSTRAINT pk_href_routing_model PRIMARY KEY (id_row),
    CONSTRAINT fk_href_routing_model_route FOREIGN KEY (routing_id) REFERENCES tb_routings (routing_id),
    CONSTRAINT fk_href_routing_model_model FOREIGN KEY (model_id) REFERENCES tb_models (model_id),
    CONSTRAINT uq_href_routing_model_route_model_loc UNIQUE (routing_id, model_id, location_id)
);

-- Indexes
CREATE INDEX ix_tb_items_model_id ON tb_items(model_id);
CREATE INDEX ix_tb_items_line_id ON tb_items(line_id);
CREATE INDEX ix_tb_items_status_id ON tb_items(status_id);
CREATE INDEX ix_tb_items_cell_id ON tb_items(cell_id);
CREATE INDEX ix_tb_items_id_user ON tb_items(id_user);
CREATE INDEX ix_tb_items_location_id ON tb_items(location_id);

CREATE INDEX ix_his_proc_item_item_id ON his_proc_item(item_id);
CREATE INDEX ix_his_proc_item_create_date ON his_proc_item(create_date);

CREATE INDEX ix_href_cell_line_cell_id ON href_cell_line(cell_id);
CREATE INDEX ix_href_cell_line_line_id ON href_cell_line(line_id);

CREATE INDEX ix_href_routing_cell_routing_id ON href_routing_cell(routing_id);
CREATE INDEX ix_href_routing_cell_cell_id ON href_routing_cell(cell_id);

CREATE INDEX ix_href_routing_model_routing_id ON href_routing_model(routing_id);
CREATE INDEX ix_href_routing_model_model_id ON href_routing_model(model_id);

-- Default statuses
INSERT INTO tb_status(id_row, status_id, description_status) VALUES (DEFAULT,'PASS','Item in PASS status');
INSERT INTO tb_status(id_row, status_id, description_status) VALUES (DEFAULT,'FAIL','Item in FAIL status');
INSERT INTO tb_status(id_row, status_id, description_status) VALUES (DEFAULT,'OK','Item in OK status');
INSERT INTO tb_status(id_row, status_id, description_status) VALUES (DEFAULT,'NOK','Item in FAIL status');
INSERT INTO tb_status(id_row, status_id, description_status) VALUES (DEFAULT,'SCRAPPED','Item in SCRAPPED status');
INSERT INTO tb_status(id_row, status_id, description_status) VALUES (DEFAULT,'REWORK','Item in REWORK status');
INSERT INTO tb_status(id_row, status_id, description_status) VALUES (DEFAULT,'PACKED','Item in PACKED status');
INSERT INTO tb_status(id_row, status_id, description_status) VALUES (DEFAULT,'QUARANTINED','Item in QUARANTINED status');
INSERT INTO tb_status(id_row, status_id, description_status) VALUES (DEFAULT,'WAITING_CHECK','Item waiting a check status');
