apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rupmes.fullname" . }}-backend
  labels:
    {{- include "rupmes.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "rupmes.databaseUrl" . | quote }}
  PRODUCTION_INGEST_API_KEY: {{ .Values.backend.env.productionIngestApiKey | quote }}
